{% set name = "libnl" %}
{% set version = "3.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/thom311/libnl/releases/download/libnl{{ version | replace('.', '_') }}/libnl-{{ version }}.tar.gz
  sha256: 2a56e1edefa3e68a7c00879496736fdbf62fc94ed3232c0baba127ecfa76874d

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libnl
    - {{ pin_subpackage('libnl', 'x.x.x') }}
  script:
    - ./configure --prefix=$PREFIX
    - make -j$CPU_COUNT
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - bison
    - flex
  host:

test:
  commands:
    - test -f "$PREFIX/lib/libnl-3.so"
    - test -f "$PREFIX/lib/libnl-cli-3.so"
    - test -f "$PREFIX/lib/libnl-genl-3.so"
    - test -f "$PREFIX/lib/libnl-idiag-3.so"
    - test -f "$PREFIX/lib/libnl-nf-3.so"
    - test -f "$PREFIX/lib/libnl-route-3.so"
    - test -f "$PREFIX/include/libnl3/netlink/types.h"

about:
  home: https://www.infradead.org/~tgr/libnl/
  license: LGPL-2.1-or-later
  license_file: COPYING
  license_family: LGPL
  summary: Netlink Library Suite
  description: |
    The libnl suite is a collection of libraries providing APIs to netlink
    protocol based Linux kernel interfaces. Netlink is a IPC mechanism primarly
    between the kernel and user space processes. It was designed to be a more
    flexible successor to ioctl to provide mainly networking related kernel
    configuration and monitoring interfaces.
  dev_url: https://github.com/tgraf/libnl-1.1-stable

extra:
  recipe-maintainers:
    - nehaljwani
